services:
  - type: web
    name: mi-bot-telegram
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: PORT
        sync: false
      - key: RENDER_EXTERNAL_HOSTNAME
        sync: false
